In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv('iris.csv')

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [6]:
iris_data_numeric = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].values
iris_data_numeric

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

# Numpy Array

In [7]:
python_list = [1,2,3]
array_from_list = np.array(python_list)

In [8]:
print(python_list)
print(array_from_list) 

[1, 2, 3]
[1 2 3]


In [9]:
array_from_list[1]

np.int64(2)

In [10]:
zeros_array = np.zeros((3,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
ones_array = np.ones((3,3,3))
ones_array

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
arange_array = np.arange(0,10,1)
arange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Random Value Numpy Array
np.random.rand() -> random float<br>
np.random.randiant() -> random int

In [13]:
random_float_array = np.random.rand(5,5)
random_float_array

array([[0.14925267, 0.47271172, 0.08977551, 0.8210112 , 0.96939614],
       [0.9380287 , 0.27586386, 0.04857945, 0.0929518 , 0.36228545],
       [0.03645294, 0.72919819, 0.72887767, 0.9231902 , 0.47913735],
       [0.61538528, 0.74144031, 0.57096252, 0.42324312, 0.56168539],
       [0.48418008, 0.9474425 , 0.39551992, 0.62506298, 0.72242287]])

In [14]:
random_int_array = np.random.randint(0,10, size=(3,3))
random_int_array

array([[9, 3, 0],
       [7, 0, 9],
       [9, 5, 7]], dtype=int32)

In [15]:
old_array = np.arange(1,11)
old_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:

old_array_reshaped = old_array.reshape(5,2)
old_array_reshaped


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Indexing and Slicing

In [17]:
iris_data_numeric[0, 0]

np.float64(5.1)

In [18]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [19]:
# [row, column] -> [start:end:step, start:end:step]
iris_data_numeric[0:5, 0:2]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [20]:
iris_data_numeric[:, -2:] # -1

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.5, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [21]:
sepal_length_gt_5 = iris_data_numeric[iris_data_numeric[:, 0] > 5.0]
sepal_length_gt_5

array([[5.1, 3.5, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2

# Operasi Numpy (Aritmatika & Aggregation)

In [22]:
data15 = np.arange(1, 6)
data510 = np.arange(6, 11)


In [23]:
data15.shape

(5,)

In [24]:
data510.shape

(5,)

In [25]:
data_sum = data15 * 5
data_sum

array([ 5, 10, 15, 20, 25])

In [26]:
data_substrac = data510 - data15
data_substrac

array([5, 5, 5, 5, 5])

# Numpy Part 2: Broadcasting
Day 9

In [58]:
data = np.random.randint(10,100,size=(3,3))
data

array([[13, 17, 88],
       [94, 49, 10],
       [45, 23, 50]], dtype=int32)

In [53]:
data_sqrt = np.sqrt(data)
data_sqrt

array([[9.2736185 , 3.60555128, 3.31662479],
       [4.79583152, 9.59166305, 6.4807407 ],
       [8.36660027, 9.        , 8.60232527]])

In [54]:
data_log = np.log(data)
data_log

array([[4.4543473 , 2.56494936, 2.39789527],
       [3.13549422, 4.52178858, 3.73766962],
       [4.24849524, 4.39444915, 4.30406509]])

In [50]:
data_log_2 = np.log2(data)
data_log_2

array([[6.        , 6.55458885, 4.70043972],
       [6.20945337, 4.5849625 , 5.08746284],
       [5.95419631, 5.97727992, 6.59991284]])

# Dot Product & Matrix Multiplication


In [31]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
hasil = np.dot(v1, v2)
hasil

np.int64(32)

In [32]:
m1 = np.array([[2,3,1],
               [7,6,1]])
m2 = np.array([[1,2],
               [5,3],
               [1,1]])

hasil = np.dot(m1,m2)       #lebih bagik pakai yang ini saja
hasil

array([[18, 14],
       [38, 33]])

In [33]:
hasil = m1 @ m2         #alternative penggunan dot untuk matrix
hasil

array([[18, 14],
       [38, 33]])

In [34]:
hasil = np.matmul(m1,m2)         #alternative penggunan dot untuk matrix
hasil

array([[18, 14],
       [38, 33]])

# Broadcasting

In [35]:
# vector dengan scalar
v = np.array([1,2,3])
s = 10

hasil = v + s
hasil

array([11, 12, 13])

In [36]:
# matrix dengan vektor
M = np.array([[1,2,3],
             [4,5,6]])
V = np.array([10,20,30])

hasil = M + V               # untuk pertambahan ini akan bisa tapi untuk perkalian ini tidak bisa
hasil                       # jika di perkalian ini hanya operasi perkalian normal

array([[11, 22, 33],
       [14, 25, 36]])

In [37]:
M = np.array([[1,2,3],
             [4,5,6]])
V = np.array([[100],
             [200]])

hasil = M + V
hasil    


array([[101, 102, 103],
       [204, 205, 206]])

In [38]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [39]:
iris_data_numeric_tambahan = iris_data_numeric[:,3] + 0.5
iris_data_numeric_tambahan

array([0.7, 0.7, 0.7, 0.7, 0.7, 0.9, 0.8, 0.7, 0.7, 0.6, 0.7, 0.7, 0.6,
       0.6, 0.7, 0.9, 0.9, 0.8, 0.8, 0.8, 0.7, 0.9, 0.7, 1. , 0.7, 0.7,
       0.9, 0.7, 0.7, 0.7, 0.7, 0.9, 0.6, 0.7, 0.6, 0.7, 0.7, 0.6, 0.7,
       0.7, 0.8, 0.8, 0.7, 1.1, 0.9, 0.8, 0.7, 0.7, 0.7, 0.7, 1.9, 2. ,
       2. , 1.8, 2. , 1.8, 2.1, 1.5, 1.8, 1.9, 1.5, 2. , 1.5, 1.9, 1.8,
       1.9, 2. , 1.5, 2. , 1.6, 2.3, 1.8, 2. , 1.7, 1.8, 1.9, 1.9, 2.2,
       2. , 1.5, 1.6, 1.5, 1.7, 2.1, 2. , 2.1, 2. , 1.8, 1.8, 1.8, 1.7,
       1.9, 1.7, 1.5, 1.8, 1.7, 1.8, 1.8, 1.6, 1.8, 3. , 2.4, 2.6, 2.3,
       2.7, 2.6, 2.2, 2.3, 2.3, 3. , 2.5, 2.4, 2.6, 2.5, 2.9, 2.8, 2.3,
       2.7, 2.8, 2. , 2.8, 2.5, 2.5, 2.3, 2.6, 2.3, 2.3, 2.3, 2.6, 2.1,
       2.4, 2.5, 2.7, 2. , 1.9, 2.8, 2.9, 2.3, 2.3, 2.6, 2.9, 2.8, 2.4,
       2.8, 3. , 2.8, 2.4, 2.5, 2.8, 2.3])

# np.concatenate

In [40]:
array1 = np.array([[1,2],
                   [3,4]])
array2 = np.array([[5,6]])

array_gabungan = np.concatenate((array1, array2), axis=0)
array_gabungan

# axis 0 = rows
# axis 1 = columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
array1 = np.array([[1,2],
                   [3,4]])
array2 = np.array([[5],
                   [6]])

# kalau kita paksain pakai axios 0
# array1 = np.array([[1,2],
#                    [3,4],
#                    [5],
#                    [6]])

array_gabungan = np.concatenate((array1, array2), axis=1)
array_gabungan
# seperti ini cara penggabungan array

array([[1, 2, 5],
       [3, 4, 6]])